# Generated by Django 5.0.6 on 2024-07-05 16:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_Id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('firstName', models.CharField(default=None, max_length=15)),
                ('lastName', models.CharField(default=None, max_length=15)),
                ('email', models.EmailField(default=None, max_length=30, unique=True)),
                ('password', models.CharField(default=None, max_length=20, null=True)),
                ('phone', models.CharField(default=None, max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('orgId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=20)),
                ('description', models.CharField(default=None, max_length=100)),
                ('user', models.ManyToManyField(related_name='User', to='App.user')),
            ],
        ),
    ]
