# Generated by Django 5.0.6 on 2024-07-05 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='user',
            field=models.ManyToManyField(related_name='user_organisation', to='App.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
