# Generated by Django 5.0.6 on 2024-07-05 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_alter_organisation_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
