# Generated by Django 5.0.6 on 2024-07-05 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_alter_organisation_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
    ]
