# Generated by Django 5.0.6 on 2024-07-07 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_alter_user_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='user',
        ),
        migrations.AddField(
            model_name='organisation',
            name='users',
            field=models.ManyToManyField(related_name='User', to='App.user'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='description',
            field=models.TextField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='firstName',
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='lastName',
            field=models.CharField(default=None, max_length=15),
        ),
    ]
