# Generated by Django 5.0.6 on 2024-07-10 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_remove_organisation_user_organisation_users_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='users',
            field=models.ManyToManyField(related_name='user', to='App.user'),
        ),
    ]
