# Generated by Django 5.0.6 on 2024-07-11 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0015_alter_organisation_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_Id',
            new_name='userId',
        ),
    ]
